### ISSUE TITLE
empty 23mer and 30mer files with custom test

### ISSUE THREAD

**Issue by Sanrrone** [RTH-tools/crispron#1]
Dears,
I'm trying to predict activity values for sgRNA 23mer only (NGG pam included). But, when I try with a simple test.fasta
```
>sgrnatest
CATGCTAGCTAGGCTAGCTAGGG
```
the first error I got is that RNAfold accept a minimum of 30 nucleotides. So, I decided to make up a little bit my test sequence
```
AAAAAAACATGCTAGCTAGGCTAGCTAGGG
```
(notice I added Ax7). But the 23mer and 30mer files are empty. Checking the python code is because the PAM position, so I solved by added two more AA at the end and remove two from the begining.
```
AAAAACATGCTAGCTAGGCTAGCTAGGGAA
```
The software runs like a charm.
```
ID,30mer,CRISPRon
sgrnatest_p_7,AAAAACATGCTAGCTAGGCTAGCTAGGGAA,18.25
```
thus my question are, 
* why I need to give a 30mer sequence if my sgRNA is only 20 (23 if pam is included)?
* I know the input is for larger sequences, small genes size or similar, could be a only 23mer sequence input added? at the end the activity prediction is for sgRNA only
* why 23mer file is generated withouth score even though the software works only with 30mer sequences?

thanks very much in advance for your support!.
Sandro

**Comment by RTH-tools** [comment]
Hi Sandro,

You've done what you could by extending the sequence.

The reason that the 20mer is not enough that the efficiency is known to depend on not only the sgRNA+PAM but also on the sequence upstream of the guide binding site as well as downstream of the PAM. Therefore you get the best model if you can feed in the correct full 30mer of the binding site. The number 30 is a bit arbitrary and is mainly from historical and previous analysis of the CRISPR efficiencies. 

Some properties are not dependent on the full 30mer and the 23mer file is used by the subprogram which computes the energy properties of the binding.

You are also welcome to try out the webserver on https://rth.dk/resources/crispr/crispron which will give you extra information and 
a nicer user interface.

C
