### ISSUE TITLE
reference genome

### ISSUE THREAD

**Issue by Huanle** [RTH-tools/crispron#3]
Hi Cripron/off developers,

Thanks a lot for bringing these tools (criprOn/Off) to the community.
In the introduction of using the local command version of these tools, I did see any operation on the reference genomes. 
Does this mean it computes relevant scores/metrics without the need for reference genome sequences?

Thanks heaps and I look forward to your reply.

Best,
Huanle

**Comment by RTH-tools** [comment]
Hi Huanle,
All the CRISPRon program needs to predict an efficiency is a piece of sequence, at least 30 nt long with a 4 nt prefix, a 20 nt gRNA, a 3 nt PAM and a 3 nt suffix. The software has been trained on artificial sequences in human cell lines, and in the paper we show that these efficiencies translate to real efficiencies in human tissues to a reasonable degree. We believe that the method works well also for other mammalian genomes, but the further away from human the species is, the less precise the predictions will be. What genome are you interested in?
